version: 2

project_name: sejm-mcp

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: default
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
        #      - arm64
    main: ./cmd/sejm-mcp
    binary: sejm-mcp
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds_info:
      group: root
      owner: root
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

dockers_v2:
  - id: sejm-mcp-docker
    images:
      - "ghcr.io/janisz/sejm-mcp"
    tags:
      - "v{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
    dockerfile: Dockerfile

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "--yes"
      - "${artifact}@${digest}"

sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: janisz
    name: sejm-mcp
